# Generated by Django 3.1.2 on 2021-03-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('sprite_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='')),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.ability')),
            ],
        ),
    ]
