# Generated by Django 3.1.2 on 2021-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210314_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
