# Generated by Django 3.1.2 on 2021-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20210314_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sprite',
        ),
        migrations.AddField(
            model_name='ability',
            name='effect',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
