# Generated by Django 3.1.2 on 2021-03-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20210317_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='sprite_url',
            new_name='sprite',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='_id',
        ),
    ]
