# Generated by Django 3.1.2 on 2021-03-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20210317_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
