# Generated by Django 3.1.2 on 2021-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemon__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
